# Generated by Django 2.2.7 on 2019-11-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_date',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Дата устройства'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_record',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Трудовая книжка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Паспорт'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_account',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Лицевой счет'),
        ),
        migrations.AddField(
            model_name='profile',
            name='positions',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Зарплата'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('1', 'мужской'), ('2', 'женский')], default='мужской', max_length=15, verbose_name='пол'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('1', 'клиент'), ('2', 'сотрудник')], default='клиент', max_length=15, verbose_name='Категория'),
        ),
    ]
