# Generated by Django 2.2.7 on 2019-11-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191116_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='car',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Закупочная цена'),
        ),
        migrations.AddField(
            model_name='car',
            name='sales_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Продажная цена'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('1', 'в наличии'), ('2', 'не в наличии'), ('3', 'в ремонте')], default='в наличии', max_length=15, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('1', 'клиент'), ('2', 'менеджер'), ('3', 'администратор')], default='клиент', max_length=15, verbose_name='Категория'),
        ),
    ]
