# Generated by Django 2.2.7 on 2019-11-16 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_repair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repair',
            options={'verbose_name': 'Ремонтная работа', 'verbose_name_plural': 'Ремонтные работы'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'покупка'), ('2', 'ремонт')], max_length=15, verbose_name='Тип заказа')),
                ('status', models.CharField(choices=[('1', 'заявка'), ('2', 'в процессе'), ('2', 'выполнен')], default='заявка', max_length=15, verbose_name='пол')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('price', models.CharField(blank=True, max_length=30, null=True, verbose_name='Итоговая стоимость')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hello', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hi', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
