# Generated by Django 2.2.7 on 2019-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191116_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('1', 'автоматическая'), ('2', 'механическая')], max_length=15, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'заявка'), ('2', 'в процессе'), ('2', 'выполнен')], default='заявка', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Количество'),
        ),
    ]
