# Generated by Django 2.2.7 on 2019-11-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191116_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cars',
            field=models.ManyToManyField(to='core.Car', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='order',
            name='repair',
            field=models.ManyToManyField(to='core.Repair', verbose_name='Ремонтная работа'),
        ),
        migrations.AddField(
            model_name='order',
            name='sparepart',
            field=models.ManyToManyField(to='core.Sparepart', verbose_name='Запчасть'),
        ),
    ]
