# Generated by Django 2.2.7 on 2019-11-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191117_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cars',
            field=models.ManyToManyField(to='core.Car', verbose_name='Автомобили'),
        ),
        migrations.AlterField(
            model_name='order',
            name='repair',
            field=models.ManyToManyField(to='core.Repair', verbose_name='Ремонтные работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sparepart',
            field=models.ManyToManyField(to='core.Sparepart', verbose_name='Запчасти'),
        ),
    ]
