# Generated by Django 2.2.7 on 2019-11-17 15:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191117_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('1', 'в наличии'), ('2', 'не в наличии'), ('3', 'в ремонте'), ('3', 'принятый')], default='принятый', max_length=15, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='repair',
            field=models.ManyToManyField(blank=True, null=True, to='core.Repair', verbose_name='Ремонтные работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sparepart',
            field=models.ManyToManyField(blank=True, null=True, to='core.Sparepart', verbose_name='Запчасти'),
        ),
    ]
