# Generated by Django 2.2.7 on 2019-11-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191117_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sales_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('1', 'в наличии'), ('2', 'не в наличии'), ('3', 'в ремонте'), ('4', 'принятый')], default='4', max_length=15, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'заявка'), ('2', 'в процессе'), ('3', 'выполнен')], default='1', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'мужской'), ('2', 'женский')], max_length=15, null=True, verbose_name='пол'),
        ),
    ]
