# Generated by Django 2.2.7 on 2019-11-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191117_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(default=1, max_length=20, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('1', 'в наличии'), ('2', 'не в наличии'), ('3', 'в ремонте'), ('4', 'принятый')], default='4', max_length=15, verbose_name='Статус'),
        ),
    ]
