# Generated by Django 2.2.7 on 2019-11-19 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191119_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinorder',
            name='car',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='carinorder',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),
        migrations.AlterField(
            model_name='repairinorder',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),
        migrations.AlterField(
            model_name='repairinorder',
            name='repair',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Repair', verbose_name='Ремонтная работа'),
        ),
        migrations.AlterField(
            model_name='sparepartinorder',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),
        migrations.AlterField(
            model_name='sparepartinorder',
            name='sparepart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sparepart', verbose_name='Запчасть'),
        ),
    ]
