# Generated by Django 2.2.7 on 2019-11-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191119_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='car',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_account',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Лицевой счет'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Продажная цена'),
        ),
    ]
