# Generated by Django 2.2.7 on 2019-11-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191120_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='type',
            field=models.CharField(choices=[('1', 'в наличии'), ('2', 'не в наличии')], default='в наличии', max_length=15, verbose_name='Категория'),
        ),
    ]
