# Generated by Django 2.2.7 on 2019-11-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191122_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('покупка', 'покупка'), ('ремонт', 'ремонт')], max_length=15, verbose_name='Тип заказа'),
        ),
    ]
