# Generated by Django 2.2.7 on 2019-11-22 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191122_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinorder',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная стоимость'),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная стоимость'),
        ),
        migrations.AddField(
            model_name='sparepartinorder',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная стоимость'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная стоимость')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Прибыль')),
                ('status', models.CharField(choices=[('1', 'выставлен'), ('2', 'оплачен')], default='1', max_length=15, verbose_name='Статус')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Order', verbose_name='Заказ')),
            ],
        ),
    ]
