# Generated by Django 2.2.7 on 2019-11-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20191123_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата устройства'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='positions',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='type',
            field=models.CharField(choices=[('1', 'в наличии'), ('2', 'не в наличии')], default='в наличии', max_length=15, verbose_name='Статус'),
        ),
    ]
