# Generated by Django 2.2.7 on 2019-11-23 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20191123_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['mark'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'ordering': ['name'], 'verbose_name': 'Ремонтная работа', 'verbose_name_plural': 'Ремонтные работы'},
        ),
        migrations.AlterModelOptions(
            name='sparepart',
            options={'ordering': ['name'], 'verbose_name': 'Запчасть', 'verbose_name_plural': 'Запчасти'},
        ),
        migrations.AlterField(
            model_name='car',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='carinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='carinorder',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Закупочная стоимость'),
        ),
        migrations.AlterField(
            model_name='carinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Закупочная стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='repairinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='repairinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='report',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Прибыль'),
        ),
        migrations.AlterField(
            model_name='report',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Закупочная стоимость'),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='sparepartinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='sparepartinorder',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Закупочная стоимость'),
        ),
        migrations.AlterField(
            model_name='sparepartinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итого'),
        ),
    ]
